services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: kaiyicode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  kaiyicode-api:
    container_name: kaiyicode-api
    image: kaiyicode1/kaiyicode-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  kaiyicode-react:
    container_name: kaiyicode-react
    image: kaiyicode1/kaiyicode-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - kaiyicode-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: